### PR TITLE
TLS Protocols configuration option

### PR DESCRIPTION
**Pull request by tapiiron**

### CODE REVIEW

**Comment by tapiiron** [comment]
Seems like TLS 1.3 support can be activated only after Java 11. With Java 8 it does not work.

**Comment by larsnaesbye** [comment]
Is there any reason why we should not require Java 11 anyway?

**Comment by tapiiron** [comment]
No, I do not think there should be any reason to support older Java versions

**Comment by larsnaesbye** [comment]
@brasseld This seems like a real cool PR (when the conflict has been fixed) . To limit the allowed TLS versions is very useful.

**Comment by brasseld** [comment]
Hi @tapiiron 

Can you squash the 4 commits into a single one please ?

**Comment by brasseld** [comment]
Also, what about the cipher suite ? 
https://github.com/gravitee-io/issues/issues/4065

Want to handle to handle it from an other PR ?

**Comment by tapiiron** [comment]
Cipher Suite should be added with another PR. Tried to test that feature quickly but can not find supported cipher suite lists from javadocs(which makes it quite hard to test).

Seems like my github skills do not include squashing the commits unless i recreate the merge request.

**Comment by tapiiron** [comment]
Created new pull request Issue #583 .

**Pull request closed without merging**
