### PR TITLE
https://github.com/gravitee-io/issues/issues/2971

### PR DESCRIPTION
**Pull request by brightlizard**

### CODE REVIEW

**Comment by brasseld** [comment]
Hey @brightlizard 

Why not reporting context attributes as part of the request metrics instead of using a new object?

**Comment by brightlizard** [comment]
@brasseld Do you offer to add context attributes to Metrics or Log objects of gravitee-reporter-api
 module?

**Comment by brightlizard** [comment]
@brasseld please see previous comment

**Comment by brightlizard** [comment]
@NicolasGeraud please see the PR

**Comment by brasseld** [comment]
Hi @brightlizard 

Thanks for the PR.

I'm still asking myself if it makes sense to have a dedicated reporter processor and also a dedicated reportable.

IMHO, these context attributes must be stored only when logging is enabled for the API so I would put them into the `io.gravitee.reporter.api.log.Log` object.

Perhaps in the same way as this PR: https://github.com/gravitee-io/gravitee-gateway/pull/485/files#diff-1addf6c59f976400861e43723e30d1a4R55


WDYT ?

**Comment by brightlizard** [comment]
Ou, didn't think that way for some reason, but it's looks better idea. It would be good to have most of execution context available in io.gravitee.reporter.api.log.Log object.

**Comment by brightlizard** [comment]
Hi, @brasseld! Tell me please, are you going make the discussed changes to some of the following patches?

**Comment by brasseld** [comment]
Hi @brightlizard 

Sorry I was looking for a feedback from you.
So, I think it would be better if we can add context attributes to the Request object and report them in one-shot.

The benefit of this is that we can store custom attributes, and we'll be able to rely on them to create custom dashboards also.

**Comment by brightlizard** [comment]
Ok, I don't mind, but what about add to request object sslContext and context.request().contextPath() as well?

**Comment by brasseld** [comment]
SSL info will be added to the logged request thanks to this PR: https://github.com/gravitee-io/gravitee-reporter-api/pull/35/files

About the context-path, there was no reason until now.

Why would you need the path ?

**Comment by brightlizard** [comment]
Ou, sorry, forgot about context-path. I mixed it up with another, not related, problem.

**Pull request closed without merging**
