### PR TITLE
refactor(debug): migrate sync implementation

### PR DESCRIPTION
**Pull request by gcusnieux**
gravitee-io/issues#6126

### CODE REVIEW

**Review by ytvnr — COMMENTED** [review]
just a question

**Comment by gcusnieux** [comment]
🆙 @gravitee-io/architecture

**Comment by gcusnieux** [comment]
🆙 @gravitee-io/architecture

**Review by brasseld — CHANGES_REQUESTED** [review]
As per our discussion with @gcusnieux , few changes are requested

**Review by ytvnr — COMMENTED** [review]
some comments

**Review by brasseld — APPROVED** [review]

**Pull request merged**
